In [2]:
import torch
print(torch.__version__)

2.2.2


In [3]:
import random

# Create a 3x3 matrix (list of lists) with random float values
matrix = [[random.random() for _ in range(3)] for _ in range(3)]
print(matrix)

[[0.619134977495512, 0.08549201366460446, 0.7131324843273845], [0.09309413330491856, 0.8213168040966277, 0.6343137927328008], [0.8821793801622586, 0.7902983041501873, 0.587367005828046]]


In [4]:
import torch

tensor1 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
tensor2 = torch.tensor([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0], [3.0, 2.0, 1.0]])

# Element-wise addition
result = tensor1 + tensor2
print(result)

tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])


In [5]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reshaped_tensor = tensor.view(1, 9)
print(reshaped_tensor)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [6]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Basic slicing
sliced_tensor = tensor[:, 1]  # Select all rows in the second column
print(sliced_tensor)

# Boolean indexing
boolean_tensor = tensor[tensor > 5]  # Select elements greater than 5
print(boolean_tensor)

tensor([2, 5, 8])
tensor([6, 7, 8, 9])


In [7]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
concatenated_tensor = torch.cat((tensor1, tensor2), dim=0)  # Concatenate along rows
print(concatenated_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [8]:
stacked_tensor = torch.stack((tensor1, tensor2), dim=1)  # Stack along columns
print(stacked_tensor)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [10]:
tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(tensor.shape)  # Shape of the tensor
print(tensor.size())  # Size of the tensor

torch.Size([2, 2])
torch.Size([2, 2])


In [11]:
print(tensor.ndim)  # Number of dimensions

2
